name: .NET

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    strategy:
      matrix:
        project: ["FrameworkExe/FrameworkExe.csproj", "CoreExe/CoreExe.csproj"]

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.500
    - name: Run ${{ matrix.project }}
      run: dotnet run --project ${{ matrix.project }}
